### PR TITLE
docs: generate doc from tsdoc

### PR DESCRIPTION
**Pull request by lihbr**
## Types of changes

- [x] Chore (a non-breaking change which is related to package maintenance)
- [ ] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

This PR adds generated documentation from [TSDoc](https://tsdoc.org) using [`typedoc`](https://typedoc.org) and a fork of [`typedoc-plugin-markdown`](https://github.com/tgreyuk/typedoc-plugin-markdown/tree/master/packages/typedoc-plugin-markdown). `typedoc-plugin-markdown` has been forked to fine-tune its output a bit.

Generated documentation can be browsed here: https://github.com/prismicio/prismic-types/tree/doc/generate-doc-from-tsdoc/typedoc#readme

Related code of the fork (and the quick CLI script) is living here: https://github.com/prismicio/prismic-typedoc

The overall API is pretty limited but let me know if you have any improvement ideas!

## Checklist:

- [ ] My change requires an update to the official documentation.
- [x] All [TSDoc](https://tsdoc.org) comments are up-to-date and new ones have been added where necessary.
- [x] All new and existing tests are passing.

### CODE REVIEW

**Comment by lihbr** [comment]
TODO: turn H4 into bold to simplify GitHub TOC

**Comment by lihbr** [comment]
Updated the generator to use a more coherent sort order and disabled H4 & H5 so that TOC make sense, pretty happy with it!

**Comment by lihbr** [comment]
I don't think we'll move forward with this anymore, closing for now.

**Comment by angeloashmore** [comment]
Still a good idea, though. Maybe we can revisit when we have time.

**Pull request closed without merging**
